---
title: "SintaxisMarkDown"
author: "Edgar J"
date: "14/10/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

Probemos con un parrafo.

Ahora con un poco de código:

```{r}
fit = lm(dist ~ speed, data = cars)
b   = coef(fit)
plot(cars)
abline(fit)
```

La pendiente de la regresion es `r b[1]`.

# Sintaxis

## Formateo de linea

### Italicas
Para poner itálicas _hay que usar el simbolo_ "_", también *funciona* "*".

### Negritas
Para poder hacer **enfasis** es suficiente con el símbolo "**".

### Subscripts y overscript
x~2~, x~3~...probando x^3^, x^2^

### Links de internet
[CRAN](https://cran.r-project.org/)

### Listas
- one item
- one item
- one item
    - one more item
    - one more item
    - one more item

Hay varias formas de hacer una lista

- Con los simbolos "-", "*", "+"
- Cada uno de ellos agrega un punto
  - Se puede hacer sublistas con una indentación
    - Cada indentación agrega un lista
    
La otra forma es usar números, los cuales se pueden combinar

1. Este es primer punto
  - Con un elemento indentado
  - Y otro elemento
2. Con segundo punto
  - Con una lista anidada
    1. Con varios elementos de número
    2. Como este
    3. O este

### Citas
Es posible citar directamente en el texto por medio de ">"

> "As a rule, software systems do not work well until they have been used, and have failed repeatedly, in real applications. 

>
> --- Dave Parnas

### Expresiones matemáticas

Las expresiones matemáticas se pueden realizar por medio de LaTeX, mediante los símbolos de dólar. Por ejemplo si queremos poner en la línea, usamos el método simple $f(k) = {n \choose k} p^{k} (1-p)^{n-k}$. O lo podemos poner en modo presentación:
$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$

