#Inciso a)

Creamos una columna de 100 valores de una Unif(0,1) con la función runif.

```{r}
y <- runif(1000) # Puse 1000 para que se vea más claramente
```

#Inciso b)
Ahora haremos otro array de datos mediante la formula $-2\log(1-y)$.

```{r}
x = -2*log(1-y)
# Guardamos los datos en un dataframe
df <- data.frame(muestra = y, transformacion = x)
```

#Inciso c)
Realizamos el histograma de los datos con ggplot.
```{r}
library(ggplot2)
colores <- c("f(x)" = "red", "Muestra" = "black")

ggplot(data = df) +
  geom_histogram(aes(x = transformacion, y = stat(count / sum(count)), color = "Muestra"), bins = 10) +
  geom_line(aes(x = transformacion, y = dexp(transformacion, rate = 0.5), color = "f(x)" ),linewidth = 1) +
  scale_color_manual(values = colores) +
  labs(x = "-2log(1-y)", y = "Frecuencia", colour = NULL) +
  theme(legend.background = element_blank(),
        legend.key.size = unit(1,"cm"), 
        legend.text = element_text(size = 10),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"))

#ggsave("../ejercicio176.png", dpi = 300)

```

