# Funciones útiles.

```{r}
library(ggplot2)
```


### Graficar F empirica.

```{r}
graficar_fd <- function(D) {
  funcion_empirica <- function(x, D) {
    # Definimos la funcion de distribucion empirica para el conjunto de datos dado.
    n <- length(D)
    sumatoria <- sum(D <= x) # Sumamos 1 si X_i <= x, 0 de otra forma.

    return(sumatoria / n)
  }
  # Toma como entrada una lista de los datos. Devuelve el plot.
  x <- seq(from = min(D) - 1, to = max(D) + 1, by = 0.01)
  y <- sapply(x, FUN = function(n) funcion_empirica(n, D))
  datos <- data.frame(x = x, y = y)

  # Necesitamos estas columnas por el tipo de plot para generar
  # las discontinuidades.
  datos$xend <- c(datos$x[2:nrow(datos)], NA)
  datos$yend <- datos$y
  library(ggplot2)
  library(latex2exp)
  p <- ggplot(datos) +
    geom_segment(aes(
      x = x, y = y,
      xend = xend, yend = yend
    ), color = "black") +
    labs(x = "x", y = TeX(r'($\hat{F}(x)$)', bold = TRUE, italic = TRUE)) +
    theme(
      axis.title = element_text(face = "bold"),
      axis.title.y = element_text(vjust = 0.5),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, linewidth = 1)
    )
  return(p)
}
```


### Q-Q Plot normal

```{r}
qqnormalplot <- function(D) {
  library(ggplot2)
  # El input de la función debe ser un dataframe de una sola columna
  # que contiene a la muestra.
  # La función devuelve el plot para ser almacenado en una variable.

  # Obtenemos la media y la desviación estándar muestral.
  media_muestral <- mean(D[, 1])
  desv_muestral <- sd(D[, 1])

  # Datos para la graficación
  D[, 1] <- sort(D[, 1])
  D$p_i <- c(1:length(D[, 1])) / (length(D[, 1]) + 1)
  D$z_i <- qnorm(D$p_i)
  D$teorico <- desv_muestral * D$z_i + media_muestral

  p <- ggplot(D) +
    # Muestra
    geom_line(aes(x = z_i, y = D[, 1]), color = "black") +
    geom_point(aes(x = z_i, y = D[, 1]), color = "black", shape = 1) +
    # Normal
    geom_line(aes(x = z_i, y = teorico), color = "red", linetype = "dashed") +
    # Parámetros de visualización
    labs(title = "Gráfica Q-Q Normal", x = "Cuantil teórico", y = "Observaciones") +
    theme(
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, size = 1),
      plot.title = element_text(hjust = 0.5)
    )

  return(p)
}
```


### Q-Q Plot normal con banda de confianza.

```{r}
qqnormalplot <- function(D, banda = NULL) {
  library(ggplot2)
  library(latex2exp)
  # El input de la función debe ser un dataframe de una sola columna
  # que contiene a la muestra.
  # La función devuelve el plot para ser almacenado en una variable.

  # Obtenemos la media y la desviación estándar muestral.
  media_muestral <- mean(D[, 1])
  desv_muestral <- sd(D[, 1])

  # Datos para la graficación
  D[, 1] <- sort(D[, 1])
  D$p_i <- c(1:length(D[, 1])) / (length(D[, 1]) + 1)
  D$z_i <- qnorm(D$p_i)
  D$teorico <- desv_muestral * D$z_i + media_muestral

  p <- ggplot(D) +
    # Muestra
    geom_line(aes(x = z_i, y = D[, 1], color = "Muestra")) +
    geom_point(aes(x = z_i, y = D[, 1]), color = "black", shape = 1) +
    # Normal
    geom_line(aes(x = z_i, y = teorico), color = "red", linetype = "dashed") +
    # Parámetros de visualización
    labs(title = "Gráfica Q-Q Normal", x = "Cuantil teórico", y = "Observaciones", color = "Datos") +
    theme(
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
      plot.title = element_text(hjust = 0.5),
      legend.position = "inside",
      legend.position.inside = c(0.05, 0.95),
      legend.justification = c(0, 1)
    )

  colores <- c("black")

  if (!is.null(banda)) {
    alfa <- 1 - banda
    e_0 <- sqrt(log(2 / alfa) / (length(D[, 1]) * 2))

    D$fempirico <- sapply(D[, 1], FUN = function(x) funcion_empirica(x, D[, 1]))

    # Bandas de confianza de la funcion empirica
    L <- D$fempirico - e_0
    L[L < 0] <- 0

    U <- D$fempirico + e_0
    U[U > 1] <- 1

    # Bandas de confianza en el qqplot
    D$bandainferior <- qnorm(L)
    D$bandasuperior <- qnorm(U)

    D$bandainferior <- desv_muestral * D$bandainferior + media_muestral
    D$bandasuperior <- desv_muestral * D$bandasuperior + media_muestral

    leyenda <- paste0("1 - a = ", banda)

    p <- p +
      geom_line(data = D, mapping = aes(x = z_i, y = bandasuperior, color = leyenda), linetype = "dashed") +
      geom_line(data = D, mapping = aes(x = z_i, y = bandainferior, color = leyenda), linetype = "dashed")

    colores <- c("blue", "black")
  }

  p <- p +
    scale_color_manual(values = colores)


  return(p)
}
```





