---
title: Problema 6
---

### Inciso 2.

Primero declaramos los valores de k, y realizamos el cálculo de la varianza y la media para cada distribución con las formulas vistas en clase. 

```{r}
k <- c(1,2,3)

# Para Unif(a = -3, b = 3)
a <- -3
b <- 3
media_unif <- (a+b)/2
desv_unif <- ((a-b)**2 / 12)**0.5

p_unif <- punif(media_unif+k*desv_unif, min = a, max = b) - punif(media_unif-k*desv_unif, min = a, max = b)



# Para Normal(0,1)
media_nor <- 0
desv_nor <- 1

p_nor <- pnorm(media_nor + k*desv_nor) - pnorm(media_nor - k*desv_nor)



# Para Exponencial(2), theta = 2
theta <- 2
media_exp <- theta
desv_exp <- (theta**2)**0.5

p_exp <- pexp(media_exp + k*desv_exp, rate = 1/theta) -
  pexp(media_exp - k*desv_exp, rate = 1/theta) # En R el parametro es 1/theta




# Para Gamma(a = 2, b = 1)
a <- 2
b <- 1
media_gamma_1 <- a*b
desv_gamma_1 <- (a*b**2)**0.5

p_gamma_1 <- pgamma(media_gamma_1 + k* desv_gamma_1, shape = a, scale = b) -
  pgamma(media_gamma_1 - k*desv_gamma_1, shape = a, scale = b)




# Para Gamma(a = 3, b = 1)
a <- 3
b <- 1
media_gamma_2 <- a*b
desv_gamma_2 <- (a*b**2)**0.5

p_gamma_2 <- pgamma(media_gamma_2 + k* desv_gamma_2, shape = a, scale = b) -
  pgamma(media_gamma_2 - k*desv_gamma_2, shape = a, scale = b)



# Para Beta(a = 2, b= 2)
a <- 2
b <- 2
media_beta <- a/(a+b)
desv_beta <- ( (a*b)/( (a+b)**2 *(a+b+1) ) )**0.5

p_beta <- pbeta(media_beta + k*desv_beta, shape1 = a, shape2 = b) -
  pbeta(media_beta - k*desv_beta, shape1 = a, shape2 = b)



# Para Weibull(a=4,b=1)
a <- 4
b <- 1
media_we <- a**(-1/b) * gamma(1/b + 1)
desv_we <- (a**(-2/b) * (gamma(2/b + 1) - gamma(1/b + 1)**2))**0.5

p_weibull <- pweibull(media_we + k*desv_we, shape = b, scale = 1/a)


#Para Lognormal(mu=3, sigma = 2)
mu <- 3
sigma <- 2
media_log <- exp(2*mu + 2*sigma**2)
desv_log <- exp(2*mu + sigma**2)*(exp(sigma**2)-1)
p_log <- plnorm(media_log + k*desv_log, meanlog = mu, sdlog = sigma) -
  plnorm(media_log - k*desv_log, meanlog = mu, sdlog = sigma)

```

Guardamos toda la información dentro de un data.frame para visualizar mejor los resultados

```{r}
intervalos <- c(1,2,3)

tabla <- data.frame(k = intervalos,
                    "Unif(-3,3)" = p_unif,
                    "Normal(0,1)" = p_nor,
                    "Exp(2)" = p_exp,
                    "Gamma(2,1)" = p_gamma_1,
                    "Gamma(3,1)" = p_gamma_2,
                    "Beta(2,2)" = p_beta,
                    "Weibull(4,1)" = p_weibull,
                    "Lognormal(3,2)" = p_log)
```

